-- 게시판 작업
CREATE TABLE BOARD (
    BNO             NUMBER,
    TITLE           VARCHAR2(100)   NOT NULL,
    CONTENT         VARCHAR2(1000)  NOT NULL,
    WRITER          VARCHAR2(100)   NOT NULL,
    REGDATE         DATE    DEFAULT SYSDATE,
    MDFDATE     DATE    DEFAULT SYSDATE,
    VIEWCOUNT       NUMBER,
    CONSTRAINT PK_BOARD PRIMARY KEY(BNO)
);

CREATE SEQUENCE SEQ_BOARD;

INSERT INTO BOARD(BNO, TITLE, CONTENT, WRITER)
VALUES(SEQ_BOARD.NEXTVAL, '자바', '스프링 게시판', 'user01');

INSERT INTO BOARD(BNO, TITLE, CONTENT, WRITER)
SELECT SEQ_BOARD.NEXTVAL, TITLE, CONTENT, WRITER FROM BOARD;


SELECT BNO, TITLE, CONTENT, WRITER, REGDATE, UPDATEDDATE, VIEWCOUNT
FROM (
	    SELECT /*+INDEX_DESC(board pk_board) */
	    ROWNUM rn, BNO, TITLE, CONTENT, WRITER, REGDATE, UPDATEDDATE, VIEWCOUNT
		FROM BOARD
		WHERE  ROWNUM <= ? * ?
	)
		WHERE rn > ? * ?
</SELECT>

SELECT COUNT(*)
FROM BOARD
WHERE BNO > 0

SELECT BNO, TITLE, CONTENT, WRITER, REGDATE, UPDATEDDATE
FROM BOARD WHERE BNO = ?;